name: 'Build and Deploy to Google Cloud Run'

on:
#  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'alpine-myth-429122-g2'
  REGION: 'us-central1'
  REPO: main
  IMAGE: front-1

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout our repo for last update
        uses: 'actions/checkout@v4'

      - name: Set variables
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE" >> $GITHUB_ENV

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2' # old name: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}


